#!/bin/bash
# Copyright (c) 2000-2023 KodCloud Inc. All rights reserved.

. "$(dirname "$0")"/string_loader
. "$(dirname "$0")"/custom_common

TARGET_PATH="/var/packages/$PKG_NAME/target"
SYNOLOGY_ADDED_PATH="/var/packages/$PKG_NAME/target/synology_added"
PKG_NGINX_CONFIG="www.$PKG_NAME.conf"
NGINX_CONF_PATH="/usr/local/etc/nginx/conf.d/"

CustomRemoveBackupConf()
{
	local backup_info="/var/packages/.$PKG_DIR.conf"
	[ -s "$backup_info" ] && rm -f "$backup_info"
}

CustomRemove()
{
	:
}

CustomPreupgrade()
{
	:
}

CustomPreuninst()
{
	:
}

CustomBackupData()
{
	:
}

CustomPostuninst()
{
	:
}

CustomPreinst()
{
	:
}

CustomPostinst()
{
	:
}

CustomRestore()
{
	:
}

CustomRestoreUpgrade()
{
	:
}

CustomUseUnixSocket()
{
	:
}

CustomSetCleanNew()
{
	:
}

CustomNewInst()
{
	:
}

CustomSetInit()
{
	:
}

CustomWriteInfo()
{
	:
}

CustomPostupgrade()
{
	:
}

CustomStart()
{
	:
}

CustomStop()
{
	:
}

QuoteSQLString()
{
	sed -e 's|\\|\\\\|g' -e 's|`|\\`|g'
}

QuoteSed()
{
	sed -e 's|\\|\\\\|g' -e 's|&|\\\&|g'
}

QuotePHP()
{
	sed -e 's|\\|\\\\|g' -e "s|'|\\\\'|g"
}

QuoteSh()
{
	sed -e 's|\\|\\\\|g' -e 's|\"|\\\"|g' -e 's|`|\\`|g' -e 's|\$|\\\$|g'
}

EscapeSlashDelimiterAndSingleQuote()
{
	sed -e "s|'|\\\\'|g" -e 's|/|\\\/|g'
}

EscapeStandardSedString()
{
	QuoteSed | EscapeSlashDelimiterAndSingleQuote
}

EscapeStandardSedStringOnPHP()
{
	QuotePHP | EscapeStandardSedString
}

# must be in the last for overriding
. "$(dirname "$0")"/script_customized
