#!/bin/bash
# Copyright (c) 2015-2022 KodCloud Inc. All rights reserved.

. "$(dirname "$0")"/common

# empty
CustomPreuninst

if [ "$SYNOPKG_PKG_STATUS" = "UNINSTALL" ]; then
	rm -rf "$(GetBackupPath)" "$INFO_FILE"
# upgrade时执行备份
else
	rm -rf "$(GetBackupPath)"
	CustomBackupData
	echo "path=$(GetBackupPath)" >> "$INFO_FILE"
	echo "version=$SYNOPKG_PKGVER" >> "$INFO_FILE"
fi

exit 0
