#!/bin/bash
# Copyright (c) 2000-2017 Synology Inc. All rights reserved.

. "$(dirname "$0")"/common

if IsPreviousVersionBelowDSM7 && [ -e "$WEBSITE_ROOT" ]; then
	echo "$wizard_website_root_exist_2" >> "$SYNOPKG_TEMP_LOGFILE"
	exit 1
fi
# empty
CustomPreupgrade

if IsPreviousVersionBelow2212 ; then
	rm -rf "$(GetBackupPath)"
	CustomRemove
	CustomBackupData
	echo "path=$(GetBackupPath)" >> "$INFO_FILE"
	echo "version=$SYNOPKG_PKGVER" >> "$INFO_FILE"
fi

exit 0
