#!/bin/sh

. "$(dirname "$0")"/common

SZD_KOD="/var/packages/KodExplorer"
DESKTOP="/usr/syno/synoman/webman/3rdparty/KodExplorer"
KodExplorerTarget="${SZD_KOD}/target"
KodExplorerUI="${KodExplorerTarget}/ui"
DSM_INDEX_ADD="/usr/syno/bin/pkgindexer_add"
DSM_INDEX_DEL="/usr/syno/bin/pkgindexer_del"
WEBDIR="/var/services/web/kodexplorer"
NGINX_CONF_DIR="/usr/local/etc/nginx/conf.d/"
NGINX_ENALBE_CONF="www.KodExplorer.enable.conf"
NGINX_DISABLE_CONF="www.KodExplorer.disabled.conf"

ReturnBroken() {
	exit 150
}

StartDaemons() {

	CustomStart
	rm -f $DESKTOP
	if [ -d "$WEBDIR" ]; then
		ln -sf ${KodExplorerUI} ${DESKTOP}
		${DSM_INDEX_ADD} ${KodExplorerUI}/index.conf
	else
		echo "web/kodexplorer not found."> $SYNOPKG_TEMP_LOGFILE
		ReturnBroken
	fi

	rm -rf ${NGINX_CONF_DIR}/${NGINX_DISABLE_CONF}
	ln -sf ${KodExplorerTarget}/synology_added/${NGINX_ENALBE_CONF} ${NGINX_CONF_DIR}
}

StopDaemons()
{
	CustomStop

	${DSM_INDEX_DEL} ${KodExplorerUI}/index.conf
	rm -f ${DESKTOP}

	rm -rf ${NGINX_CONF_DIR}/${NGINX_ENALBE_CONF}
	ln -sf ${KodExplorerTarget}/synology_added/${NGINX_DISABLE_CONF} ${NGINX_CONF_DIR}
}
case "$1" in
	start)
		StartDaemons
		;;
	stop)
		StopDaemons
		;;
	restart)
		StopDaemons
		sleep 1
		StartDaemons
		;;
	status)
		if [ ! -d "/var/services/web/kodexplorer" ]; then
			rm -f $DESKTOP
			ReturnBroken
		fi
		exit 0
		;;
	log)
		LOGFILE="/tmp/KodExplorer.log"
		grep "KodExplorer:" /var/log/messages > ${LOGFILE}
		if [ $? -eq 0 ]; then
			echo "${LOGFILE}"
		fi
		;;
	*)
		echo "Usage: $0 {start|stop|restart|status|log}" >&2
		exit 1
		;;
esac

exit 0

