#!/bin/bash

. "$(dirname "$0")"/common
# empty
CustomPostinst

MoveLegacyBackupDataToDSM7BackupPath()
{
	local dsm7_backup_path="$(GetBackupPath)"
	if [ -e "$dsm7_backup_path" ]; then
		return
	fi

	local legacy_backup_path="$(GetLegacyBackupDataPrefix)"
	if [ -z "$legacy_backup_path" ] || [ ! -e "$legacy_backup_path" ]; then
		return
	fi

	echo "migrate legacy backup data in [${legacy_backup_path}] to DSM backup path"
	mv "$legacy_backup_path" "${dsm7_backup_path}"
	CustomMoveLegacyBackupWebDir "$dsm7_backup_path"
}

MoveLegacyBackupDataToDSM7BackupPath

if [ "$SYNOPKG_PKG_STATUS" = "UPGRADE" ]; then
	InitBackupPath

	DB_NAME=$(CustomGetDBName "$BACKUP_WEB_PATH")
	DB_USER=$(CustomGetDBUser "$BACKUP_WEB_PATH")
	DB_USER_PASS=$(CustomGetDBPass "$BACKUP_WEB_PATH")

	# Restore
	if CustomHasRunWebsiteSetup "$BACKUP_WEB_PATH"; then
		CustomChangeDBUserInfo "$BACKUP_WEB_PATH" "$DB_USER" "$DB_USER_PASS"

		CustomRestoreUpgrade
		CustomUseUnixSocket
	else
		CustomSetCleanNew
	fi
	chown -R $PKG_NAME:http      "$WEBSITE_ROOT"
	chown -R $PKG_NAME:$PKG_NAME "$(GetBackupPath)"
else
	# New install
	DB_NAME="$pkgwizard_db_name"
	DB_USER="$pkgwizard_db_user_account"
	DB_USER_PASS="$pkgwizard_db_user_password"
	CustomNewInst
fi

# Set initial install setting values
CustomSetInit
DBSQLImport $DB_USER $pkgwizard_db_user_password $MYSQL $pkgwizard_db_name "db error"

# Write synology.conf
echo "db_name=$DB_NAME" > "$INFO_FILE.tmp"
echo "db_user=$DB_USER" >> "$INFO_FILE.tmp"
CustomWriteInfo "$INFO_FILE.tmp" "$INFO_FILE"
mv "$INFO_FILE.tmp" "$INFO_FILE"
chown $PKG_NAME:$PKG_NAME "$INFO_FILE"

CustomRemoveBackupConf

exit 0
