#!/bin/bash

. "$(dirname "$0")"/common
# empty
CustomPostinst

if [ "$SYNOPKG_PKG_STATUS" = "UPGRADE" ]; then
	InitBackupPath

	DB_NAME=$(CustomGetDBName "$BACKUP_WEB_PATH")
	DB_USER=$(CustomGetDBUser "$BACKUP_WEB_PATH")
	DB_USER_PASS=$(CustomGetDBPass "$BACKUP_WEB_PATH")

	# Restore
	if CustomHasRunWebsiteSetup "$BACKUP_WEB_PATH"; then
		CustomChangeDBUserInfo "$BACKUP_WEB_PATH" "$DB_USER" "$DB_USER_PASS"

		CustomRestoreUpgrade
	else
		# empty
		CustomSetCleanNew
	fi
	chown -R $PKG_NAME:http      "$WEBSITE_ROOT"
	chown -R $PKG_NAME:$PKG_NAME "$(GetBackupPath)"
else
	# New install
	DB_NAME="$pkgwizard_db_name"
	DB_USER="$pkgwizard_db_user_account"
	DB_USER_PASS="$pkgwizard_db_user_password"
	# empty
	CustomNewInst
	DBSQLImport $DB_USER $DB_USER_PASS $MYSQL $DB_NAME "db error"
fi

CustomSetInit

# Write synology.conf
echo "db_name=$DB_NAME" > "$INFO_FILE.tmp"
echo "db_user=$DB_USER" >> "$INFO_FILE.tmp"
CustomWriteInfo "$INFO_FILE.tmp" "$INFO_FILE"
mv "$INFO_FILE.tmp" "$INFO_FILE"
chown $PKG_NAME:$PKG_NAME "$INFO_FILE"

CustomRemoveBackupConf

exit 0
