#!/bin/bash
# Copyright (c) 2000-2017 Synology Inc. All rights reserved.

. "$(dirname "$0")"/common

if [ "$SYNOPKG_PKG_STATUS" == "UPGRADE" ]; then
	exit 0
fi

CustomPreinst

# Check existence of website root
if [ -e "$WEBSITE_ROOT" ]; then
	echo "$wizard_website_root_exist_2" >> "$SYNOPKG_TEMP_LOGFILE"
	exit 1
fi

exit 0
