#!/bin/bash
# Copyright (c) 2000-2017 Synology Inc. All rights reserved.

. "$(dirname "$0")"/common

R_SIZE=$(df ${SYNOPKG_PKGDEST_VOL} | awk 'NR==2{print $4}')
W_SIZE=$(du -s "$WEBSITE_ROOT" | cut -f1)

if [ $R_SIZE -lt $W_SIZE ];then
	echo "${SYNOPKG_PKGDEST_VOL}-$wizard_upgrade_space_error" >> "$SYNOPKG_TEMP_LOGFILE"
	exit 1
fi
# empty
CustomPreupgrade

exit 0
