#!/bin/sh
# Copyright (C) 2000-2016 Synology Inc. All rights reserved.

case $1 in
	start)
		    exit 0
	        ;;
	    
	stop)
		    exit 0
	        ;;
	    
	status)
		    exit 0
	        ;;
	    
	*)
		    exit 1
	        ;;
esac

